dataset_type: EOTrainingDataset
id: tds-catalog
name: TDS Catalog
description: TDS catalog
classification_schema: Extension of CORINE, see https:doi.org/10.3390/rs14194772
number_of_classes: 20
extent: global
version: 1.0
created_time: 2022
updated_time: 2023
license: CC-BY-SA-4.0
doi: None
providers:
  - Pixalytics Ltd
keywords:
  - Land Cover Classification
data_sources:
  - id: sentinel2
    data_type: Optical
    platform: Sentinel-2
    resolution: 10m
classes:
  - clear water: 1
  - algal blooms: 2
  - aqueous deposits: 3
  - bare ground: 4
  - murrum soil: 5
  - sand: 6
  - grassland: 7
  - shrubland: 8
  - forest: 9
  - cropland: 10
  - palm: 11
  - buildings: 12
  - artificial surfaces: 13
  - cloud: 14
  - shadows: 15
  - plastic: 16
  - tyres: 17
  - waves: 18
  - greenhouses: 19
  - waste sites: 20
tasks:
  - id: 1
    description: Classification of waste plastics
    task_type: Semantic Segmentation
bands:
  - red
  - green
  - blue
  - alpha
image_size: 290*200
scope:
  level: dataset
  levelDescription: Pixalytics Plastics Training Dataset
data:
  task_type: SemanticSegmentation
  label_type: PixelLabel
  data_path:
    - type: image
      format: .tif
      root_path: s3://pixalytics-ogc-api/TrainingDML-AI/input/image
    - type: label
      format: .tif # Need .json for stac file to be picked up
      root_path: s3://pixalytics-ogc-api/TrainingDML-AI/input/label
