dataset_type: EOTrainingDataset
id: tds-catalog
name: TDS Catalog
description: TDS catalog
version: 1.0
created_time: 2022
updated_time: 2022
license: CC-BY-SA-4.0
providers:
  - Pixalytics Ltd
keywords:
  - Land Cover Classification
classes:
  - Land Cover
tasks:
  - description: xxx
    task_type: xxx
data_sources:
  - id: image_id
    data_type: Optical Image
    format: tif
bands:
  - red
  - green
  - blue
  - alpha
image_size: 290*200
data:
  task_type: SemanticSegmentation
  label_type: PixelLabel
  data_path:
    - type: image
      format: stac
      root_path: /home/seadas/shared/ogcapi/input-TDS/rgb
    - type: label
      format: stac
      root_path: /home/seadas/shared/ogcapi/input-TDS/label