
#  Testing url
url: "https://pixalytics-ogc-api.s3.eu-west-2.amazonaws.com/EO4SAS/classification/20200831T101156_rgb_classification.tif"

#  Output director.
output_dir: "../ogcapi/CATALOG"

# Catalog Id
catalog_id: "eo4sas-catalog"

# Catalog description
catalog_desc: "EO4SAS catalog"

# Image Id
image_id: "20200831T101156_rgb_classification"

# YAML for API Records
yaml_file: "./eo4sas-record.yml"