
#  Testing url
url: "https://pixalytics-ogc-api.s3.eu-west-2.amazonaws.com/TDS/input/20200831T101156_rgb_classification.tif"

#  Output director.
output_dir: "./ogcapi/CATALOG"

# Catalog Id
catalog_id: "tds-catalog"

# Catalog description
catalog_desc: "TDS catalog"

# Image Id
image_id: "image_id"

# YAML for API Records
yaml_file: "./tds-record.yml"